USE [VehicleTrader]
GO

INSERT INTO [dbo].[VehicleFactory]
           ([FactoryName])
     VALUES
           ('Acura'),
		   ('Adler'),
		   ('Aero'),
		   ('AION'),
		   ('Alfa Romeo'),
		   ('AMC'),
		   ('Anaig'),
		   ('Aro'),
		   ('Asia'),
		   ('Aston Martin'),
		   ('ATS Corsa'),
		   ('Audi'),
		   ('BAIC'),
		   ('Baojun'),
		   ('Barkas'),
		   ('Baw'),
		   ('Beijing'),
		   ('Bentley'),
		   ('BMW'),
		   ('BMW-Alpina'),
		   ('Brilliance'),
		   ('Bristol'),
		   ('Buick'),
		   ('BYD'),
		   ('Cadillac'),
		   ('Chana'),
		   ('Changan'),
		   ('Changhe'),
		   ('Chanje'),
		   ('Chery'),
		   ('Chevrolet'),
		   ('Chrysler'),
		   ('Citroen'),
		   ('Cupra'),
		   ('Dacia'),
		   ('Dadi'),
		   ('Daechang'),
		   ('Daewoo'),
		   ('DAF'),
		   ('Dagger'),
		   ('Daihatsu'),
		   ('Derways'),
		   ('DFSK'),
		   ('DKW'),
		   ('Holden'),
		   ('Dodge'),
		   ('Dongfeng'),
		   ('Dr. Motor'),
		   ('DS'),
		   ('Eagle'),
		   ('Ernst Auwarter'),
		   ('FAW'),
		   ('Ferrari'),
		   ('Fiat'),
		   ('Fiat-Abarth'),
		   ('Fisker'),
		   ('Ford'),
		   ('FSO'),
		   ('FUQI'),
		   ('Geely'),
		   ('Genesis'),
		   ('Geo'),
		   ('GMC'),
		   ('Golf Car'),
		   ('Gonow'),
		   ('Great Wall'),
		   ('Groz'),
		   ('Hafei'),
		   ('Hanomag'),
		   ('Haval'),
		   ('Honda'),
		   ('Hongqi'),
		   ('Horch'),
		   ('Huabei'),
		   ('Hummer'),
		   ('Hyundai'),
		   ('Ideal'),
		   ('Infiniti'),
		   ('Iran Khodro'),
		   ('Isuzu'),
		   ('Iveco'),
		   ('JAC'),
		   ('JAC-Volkswagen'),
		   ('Jaguar'),
		   ('JCB'),
		   ('Jeep'),
		   ('Jetour'),
		   ('Jinbei'),
		   ('Karosa'),
		   ('Kia'),
		   ('King Long'),
		   ('Kirkham'),
		   ('Lada'),
		   ('Lamborghini'),
		   ('Lancia'),
		   ('Land Rover'),
		   ('Landwind'),
		   ('LDV'),
		   ('Leap Motor'),
		   ('Leopaard'),
		   ('Lexus'),
		   ('Lifan'),
		   ('Lincoln'),
		   ('Link Tour'),
		   ('MAN'),
		   ('Marshell'),
		   ('Maruti'),
		   ('Maserati'),
		   ('Maxus'),
		   ('Maybach'),
		   ('Mazda'),
		   ('McLaren'),
		   ('MEGA'),
		   ('Mercedes-Benz'),
		   ('Mercury'),
		   ('MG'),
		   ('MINI'),
		   ('Mitsubishi'),
		   ('Mobility Ventures'),
		   ('MPM Motors'),
		   ('Neta'),
		   ('NIO'),
		   ('Nissan'),
		   ('Opel'),
		   ('Packard'),
		   ('Peterbilt'),
		   ('Peugeot'),
		   ('Plymouth'),
		   ('Polestar'),
		   ('Pontiac'),
		   ('Porsche'),
		   ('Proton'),
		   ('Quicksilver'),
		   ('Ram'),
		   ('Ravon'),
		   ('Renault'),
		   ('Rivian'),
		   ('Rolls-Royce'),
		   ('Rover'),
		   ('Saab'),
		   ('Saipa'),
		   ('Samand'),
		   ('Samsung'),
		   ('Saturn'),
		   ('Scion'),
		   ('SEAT'),
		   ('Skoda'),
		   ('SMA'),
		   ('Smart'),
		   ('SouEast'),
		   ('SsangYong'),
		   ('Subaru'),
		   ('Suzuki'),
		   ('Tarpan Honker'),
		   ('TATA'),
		   ('Tatra'),
		   ('Tesla'),
		   ('Tianma'),
		   ('Tiger'),
		   ('Toyota'),
		   ('Triumph'),
		   ('Van Hool'),
		   ('Vauxhall'),
		   ('Venucia'),
		   ('Volkswagen'),
		   ('Volvo'),
		   ('Voyah'),
		   ('Wanderer'),
		   ('Wanfeng'),
		   ('Wartburg'),
		   ('Weltmeister'),
		   ('Xpeng'),
		   ('Yema'),
		   ('Zastava'),
		   ('Zotye'),
		   ('Zuk'),
		   ('ZX'),
		   ('ZAZ')
GO